name: Benchmark

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.org'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.lisp }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin/1.12.2, ecl/23.9.9]
        os: [ubuntu-latest]
    env:
      LISP: ${{ matrix.lisp }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Lisp
        continue-on-error: true
        uses: 40ants/setup-lisp@v2
        with:
          qlfile-template: |
            dist ultralisp http://dist.ultralisp.org

      - name: Run benchmarks
        shell: bash
        run: |
          echo "Base benchmark"
          ros run --eval '(ql:quickload :frugal-uuid/benchmark)' --eval '(progn (asdf:test-system :frugal-uuid/benchmark) (quit))'
          echo "Non-frugal benchmark"
          ros run --eval '(ql:quickload :frugal-uuid/*)' --eval '(progn (asdf:test-system :frugal-uuid/benchmark) (quit))'
