name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.org'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test:
    name: ${{ matrix.lisp }} / ${{ matrix.quicklisp-dist }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin/1.12.2, ecl/23.9.9]
        os: [ubuntu-latest, windows-latest, macos-latest]
        quicklisp-dist:
          - ultralisp
        exclude:
          - os: windows-latest
            lisp: ecl/23.9.9
    env:
      LISP: ${{ matrix.lisp }}
      QUICKLISP_DIST: ${{ matrix.quicklisp-dist }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Lisp
        continue-on-error: true
        uses: 40ants/setup-lisp@v2
        with:
          qlfile-template: |
            {% ifequal quicklisp_dist "ultralisp" %}
            dist ultralisp http://dist.ultralisp.org
            {% endifequal %}

      - name: Run tests (Non-Windows)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ros install neil-lindquist/ci-utils
          run-fiveam -e t -l frugal-uuid/test :frugal-uuid
          run-fiveam -e t -l frugal-uuid/non-frugal -l frugal-uuid/test :frugal-uuid

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          ros --eval '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)' --eval '(uiop:quit)'
          ros install neil-lindquist/ci-utils
          run-fiveam -e t -l frugal-uuid/test :frugal-uuid
          run-fiveam -e t -l frugal-uuid/non-frugal -l frugal-uuid/test :frugal-uuid
