name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.org'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin/1.13, ecl/24.5.10]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - os: windows-latest
            lisp: ecl/24.5.10
          - os: windows-latest
            lisp: ccl-bin/1.13
          - os: macos-latest
            lisp: ccl-bin/1.13
    env:
      LISP: ${{ matrix.lisp }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Lisp
        uses: 40ants/setup-lisp@v4
        with:
          qlfile-template: |
            dist ultralisp http://dist.ultralisp.org

      - name: Run tests (Non-Windows)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ros install neil-lindquist/ci-utils
          asdf-register-project
          run-fiveam -e t -l frugal-uuid/test :frugal-uuid
          run-fiveam -e t -l frugal-uuid/non-frugal -l frugal-uuid/test :frugal-uuid

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          ros --eval '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)' --eval '(uiop:quit)'
          ros install neil-lindquist/ci-utils
          asdf-register-project
          run-fiveam -e t -l frugal-uuid/test :frugal-uuid
          run-fiveam -e t -l frugal-uuid/non-frugal -l frugal-uuid/test :frugal-uuid
